# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ce2df1b3c6b5c875306b66fded5941fd07140cfd78d0406ad2d43aca74e4abeab8fbeee0fb1bb950a59e356c88f149de725aa47e0b8ece488988a84f8fbe4ac

test:
  secret_key_base: 3cee00bde8bcbe765839f0d1c5ff4fa44d15fda6397141671011e0aced67a86314a88693520ee82a9f73b107b4562fb05658495e11bc1988782d0026267754ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
